import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import PrintButton from "@/components/PrintButton";
import ShareButton from "@/components/ShareButton";
import { RequisitionBrand } from "@/components/RequisitionBrand";
import { cx, secret, api } from "@/lib/convex";

function money(n: number) {
  return n.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export default async function PettyCashRequisition({ params }: { params: Promise<{ id: string }> }) {
  const session = await getSession();
  if (!session || !session.orgId) redirect("/login");

  const { id } = await params;
  let row;
  try {
    row = await cx().query(api.pettyCash.getPettyCash, {
      secret: secret(),
      orgId: session.orgId as never,
      id: id as never,
    });
  } catch {
    row = null;
  }

  if (!row) redirect("/petty-cash");
  if (session.role !== "admin" && session.role !== "manager" && row.requested_by !== session.id) {
    redirect("/petty-cash");
  }

  let org = null as { name: string; logoUrl: string | null; address?: string; city?: string; phone?: string; email?: string } | null;
  try {
    org = (await cx().query(api.organizations.getOrganization, {
      secret: secret(),
      orgId: session.orgId as never,
    })) as typeof org;
  } catch {
    org = null;
  }

  return (
    <main className="min-h-screen bg-slate-100 py-6">
      <style>{`@media print { .no-print { display: none } body { background: white } }`}</style>
      <PrintButton path="/petty-cash" />
      <div className="no-print mx-auto mb-2 flex max-w-3xl justify-end px-6">
        <ShareButton label="Share" className="btn-secondary px-3 py-1.5 text-sm" />
      </div>
      <div className="mx-auto max-w-3xl bg-white p-10 shadow-sm">
        <RequisitionBrand org={org} />
        <header className="mb-8 border-b-2 border-slate-800 pb-4 text-center">
          <h1 className="text-xl font-bold tracking-widest uppercase">Petty Cash Requisition</h1>
        </header>

        <div className="mb-6 grid grid-cols-2 gap-x-10 gap-y-3 text-sm">
          <p><span className="text-slate-500">Reference:</span> <strong>{row.requisition_no}</strong></p>
          <p><span className="text-slate-500">Date needed:</span> <strong>{String(row.date_needed)}</strong></p>
          <p><span className="text-slate-500">Requested by:</span> <strong>{String(row.requested_by_name)}</strong></p>
          <p>
            <span className="text-slate-500">Status:</span>{" "}
            <strong className="uppercase">{String(row.status)}</strong>
          </p>
        </div>

        <div className="mb-6">
          <p className="mb-1 text-sm font-semibold uppercase tracking-wide text-slate-500">Purpose</p>
          <p className="min-h-24 rounded border border-slate-300 p-3 text-sm">{String(row.purpose)}</p>
        </div>

        <div className="mb-10 flex justify-end">
          <table className="w-64 border border-slate-400 text-sm">
            <tbody>
              <tr>
                <td className="border border-slate-400 px-3 py-2 font-semibold">Amount (KES)</td>
                <td className="border border-slate-400 px-3 py-2 text-right">{money(Number(row.amount))}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="grid grid-cols-3 gap-8 text-center text-xs">
          {[["Requested by", String(row.requested_by_name)], ["Approved by (Director)", ""], ["Received by", ""], ].map(([label, sub]) => (
            <div key={label}>
              <div className="h-12 border-b border-slate-500" />
              <p className="mt-1 font-semibold uppercase tracking-wide">{label}</p>
              {sub && <p className="mt-0.5 text-slate-500">{sub}</p>}
            </div>
          ))}
        </div>

        <footer className="mt-10 border-t pt-3 text-center text-[11px] text-slate-400">
          Generated by Office Manager on {new Date().toLocaleDateString("en-GB")}
          {row.approved_at ? ` · Approved ${String(row.approved_at)}` : ""}
        </footer>
      </div>
    </main>
  );
}
